---
# defaults file for your cassandra_backup role


#cassandra_backup: "cassandra-backup"
#cassandra_snapshot_name: "cassandra-backup"
#cassandra_nfs_mount_path: "/db_backup/cassandra"

cassandra_backup: "/test_backup"
#cassandra_snapshot_name: "cassandra-backup"
cassandra_nfs_mount_path: "/tmp/test_cassandra_backup"



