---
- hosts: localhost 
  gather_facts: false  

  tasks:
    - name: Create Cassandra Snapshot Directory
      file:
        path: "{{ cassandra_backup }}"
        state: directory
        mode: 0777
        recurse: yes

    - name: Take Cassandra Snapshot All KeySpaces
      command: "nodetool snapshot -t {{ cassandra_snapshot_name }}/{{ cassandra_snapshot_number }}"
      args:
        chdir: "{{ cassandra_backup }}"
      ignore_errors: no

    - name: Compress and Upload Cassandra Snapshots
      shell: |
        cd {{ cassandra_backup }}
        find . -type d -name "*$snapshot_name*" -exec tar -czvf {}.tar.gz {} \;   
        rsync -avz --remove-source-files "$cassandra_backup_path"/*"$snapshot_name"*.tar.gz "$nfs_mount_path"   
        find "$cassandra_backup_path" -type f -name "*$snapshot_name*.tar.gz" -mtime +$days_to_keep -exec rm {} \;
      ignore_errors: no
