---
- hosts: cassandra
  become: yes
  vars_files:
    - ['{{ inventory_dir }}/secrets.yml', 'secrets/{{ env }}.yml']
  vars:
    - cassandra_backup_directory: "{{ nfs_db_backup_path }}"
    - cassandra_nfs_mount_path: "{{ nfs_mount_path }}"
  roles:
    - role: cassandra-backup
      tags: cassandra-backup
